/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.InputMismatchException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author mostafahassan
 */
public class Edit_panel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form Edit_panel
     */
    public Edit_panel() {
        initComponents();
        search_btn.addActionListener(this);
        save_btn.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        save_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rank = new javax.swing.JTextField();
        lab = new javax.swing.JLabel();
        hours_worked = new javax.swing.JTextField();
        rank1 = new javax.swing.JLabel();
        over_time = new javax.swing.JTextField();
        rank2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_search = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        total_salary = new javax.swing.JTextField();
        rank3 = new javax.swing.JLabel();

        save_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        save_btn.setText("Save");

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setText("Edit Employee");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Name:");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Address:");

        rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankActionPerformed(evt);
            }
        });

        lab.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lab.setText("Rank:");

        hours_worked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hours_workedActionPerformed(evt);
            }
        });

        rank1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rank1.setText("Hours Worked:");

        over_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                over_timeActionPerformed(evt);
            }
        });

        rank2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rank2.setText("Over Time:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("ID:");

        search_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        search_btn.setText("Search");

        total_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_salaryActionPerformed(evt);
            }
        });

        rank3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rank3.setText("Total Salary:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62)
                        .addComponent(id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(62, 62, 62)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(62, 62, 62)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(62, 62, 62)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lab)
                                        .addComponent(rank1))
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hours_worked, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rank3)
                                        .addComponent(rank2))
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(over_time, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(total_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(250, 250, 250)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(378, 378, 378))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(search_btn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab)
                    .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rank1)
                    .addComponent(hours_worked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rank2)
                    .addComponent(over_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rank3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save_btn)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankActionPerformed

    private void hours_workedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hours_workedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hours_workedActionPerformed

    private void over_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_over_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_over_timeActionPerformed

    private void total_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_salaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField hours_worked;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lab;
    private javax.swing.JTextField name;
    private javax.swing.JTextField over_time;
    private javax.swing.JTextField rank;
    private javax.swing.JLabel rank1;
    private javax.swing.JLabel rank2;
    private javax.swing.JLabel rank3;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField total_salary;
    // End of variables declaration//GEN-END:variables
 public Employee find(int id) {//gets the file with employee's data and store the data in Employee obj then return it
        int tempId;
        String tempName = "", tempAddress = "", tempRank = "";
        int tempHours_worked, tempOvertime;
        double tempTotal_salary = 0;
        try {
            Scanner myFile = new Scanner(new File(id + ".txt"));

            tempId = myFile.nextInt();
            tempName = myFile.next();
            tempAddress = myFile.next();
            tempRank = myFile.next();
            tempHours_worked = myFile.nextInt();
            tempOvertime = myFile.nextInt();

               if (myFile.hasNext()) {
                tempTotal_salary = Double.parseDouble(myFile.next());
            } else {
                JOptionPane.showMessageDialog(this, "Employee doesn't have salary", "Error", JOptionPane.ERROR_MESSAGE);
            }

            Employee tempEmployee = new Employee(tempId, tempName, tempAddress, tempRank, tempHours_worked, tempHours_worked);
            tempEmployee.setTotal_salary(tempTotal_salary);
            return tempEmployee;
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Employee Not Found", "Error", JOptionPane.ERROR_MESSAGE);
        }

        Employee tempEmployee = new Employee();
        return tempEmployee;

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        save_btn.setBackground(Color.gray);
        save_btn.setForeground(Color.white);
        search_btn.setBackground(Color.gray);
        search_btn.setForeground(Color.white);
        if (e.getSource().equals(search_btn)) {
            search_btn.setBackground(Color.black);
            search_btn.setForeground(Color.white);
            
             Employee tempEmployee = new Employee();

            tempEmployee = find(Integer.parseInt(id_search.getText()));

            id.setText(tempEmployee.getId() + "");
            name.setText(tempEmployee.getName());
            address.setText(tempEmployee.getAddress());
            rank.setText(tempEmployee.getRank());
            hours_worked.setText(tempEmployee.getHours_worked() + "");
            over_time.setText(tempEmployee.getOvertime_worked() + "");
            total_salary.setText(tempEmployee.getTotal_salary()+ "");
            File destroyFile=new File(id_search.getText()+".txt");//deletes the file with the seaech id that have been entered
            destroyFile.delete();       //error doesn't get deleted :')
            destroyFile.deleteOnExit();

        }
        else if (e.getSource().equals(save_btn)) {
             try {//check to see if all fields is entered
                if (id.getText() == "" || name.getText() == "" || address.getText() == "" || rank.getText() == "" || hours_worked.getText() == "" || over_time.getText() == "") {
                    throw new Exception("Please enter all the fields");
                } else {
                    try {//gets the data form text fileds to obj employee
                        Employee employee=new Employee();
                        employee.setId(Integer.parseInt(id.getText()));
                        employee.setName(name.getText());
                        employee.setAddress(address.getText());
                        employee.setRank(rank.getText());
                        employee.setHours_worked(Integer.parseInt(hours_worked.getText()));
                        employee.setOvertime_worked(Integer.parseInt(over_time.getText()));
                        //creates a file for every unique id employee to store the information 
                        
                        File f = new File(employee.getId() + ".txt");
                        if (!f.exists()) {//so if it's not found creates a new file
                            f.createNewFile();

                            PrintWriter fileWriter = new PrintWriter(f);
                            fileWriter.write(employee.getId() + " " + employee.getName() + " " + employee.getAddress() + " " + employee.getRank() + " " + employee.getHours_worked() + " " + employee.getOvertime_worked() + "\n");
                            fileWriter.close();//closes the stream
                            JOptionPane.showMessageDialog(this, "Employee Edited ", "Success", JOptionPane.NO_OPTION);
                        } else {//there is a employee with the same id 
                            JOptionPane.showMessageDialog(this, "Employee id already Exist ", "Error", JOptionPane.ERROR_MESSAGE);

                        }
                    } catch (InputMismatchException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } catch (Exception ex) {//only parsing errors will get to here
                        JOptionPane.showMessageDialog(this, "Parse Error "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Employee id already Exist ", "Error", JOptionPane.ERROR_MESSAGE);

            }

            
        }
    }
}
