/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author mostafahassan
 */
public class main extends javax.swing.JFrame implements ActionListener {

    GridBagLayout layout = new GridBagLayout();
    GridBagConstraints c = new GridBagConstraints();

    add_employee_panel add_employee_form = new add_employee_panel();
    search_panel search_form = new search_panel();
    Edit_panel edit_form=new Edit_panel();
    Payment_panel pay_form=new Payment_panel();

    /**
     * Creates new form main
     */
    public main() {
        initComponents();

        viewPanel.setLayout(layout);

        add_employee_btn.addActionListener(this);
        search_employee_btn.addActionListener(this);
        edit_employee_btn.addActionListener(this);
        payCal_employee_btn.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        add_employee_btn = new javax.swing.JButton();
        search_employee_btn = new javax.swing.JButton();
        payCal_employee_btn = new javax.swing.JButton();
        edit_employee_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        viewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_employee_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        add_employee_btn.setText("Add Employee");

        search_employee_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        search_employee_btn.setText("Search Employee");
        search_employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_employee_btnActionPerformed(evt);
            }
        });

        payCal_employee_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        payCal_employee_btn.setText("Payment Calculator");

        edit_employee_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        edit_employee_btn.setText("Edit Employee");

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_employee_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payCal_employee_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(add_employee_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_employee_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(add_employee_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(edit_employee_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(search_employee_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(payCal_employee_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_employee_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_employee_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employee_btn;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton edit_employee_btn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton payCal_employee_btn;
    private javax.swing.JButton search_employee_btn;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        c.gridx = 0;
        c.gridy = 0;
        add_employee_btn.setBackground(Color.gray);
        add_employee_btn.setForeground(Color.white);
        search_employee_btn.setBackground(Color.gray);
        search_employee_btn.setForeground(Color.white);
        payCal_employee_btn.setBackground(Color.gray);
        payCal_employee_btn.setForeground(Color.white);
        edit_employee_btn.setBackground(Color.gray);
        edit_employee_btn.setForeground(Color.white);
        if (e.getSource().equals(add_employee_btn)) {
            viewPanel.removeAll();
            viewPanel.add(add_employee_form, c);
            viewPanel.validate();
            viewPanel.repaint();

            add_employee_btn.setBackground(Color.black);
            add_employee_btn.setForeground(Color.white);
        } else if (e.getSource().equals(search_employee_btn)) {
            viewPanel.removeAll();
            viewPanel.add(search_form, c);
            viewPanel.validate();
            viewPanel.repaint();

            search_employee_btn.setBackground(Color.black);
            search_employee_btn.setForeground(Color.white);
            
        }
        else if (e.getSource().equals(edit_employee_btn)) {
            viewPanel.removeAll();
            viewPanel.add(edit_form, c);
            viewPanel.validate();
            viewPanel.repaint();
            
            
            
             edit_employee_btn.setBackground(Color.black);
            edit_employee_btn.setForeground(Color.white);
        }
        else if (e.getSource().equals(payCal_employee_btn)) {
                    viewPanel.removeAll();
            viewPanel.add(pay_form, c);
            viewPanel.validate();
            viewPanel.repaint();
            payCal_employee_btn.setBackground(Color.black);
            payCal_employee_btn.setForeground(Color.white);
        }
    }
}
