/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author mostafahassan
 */
public class search_panel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form search_panel
     */
    public search_panel() {
        initComponents();
        search_btn.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        rank1 = new javax.swing.JLabel();
        rank2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_show = new javax.swing.JLabel();
        name_show = new javax.swing.JLabel();
        rank_show = new javax.swing.JLabel();
        address_show = new javax.swing.JLabel();
        overtime_show = new javax.swing.JLabel();
        hours_worked_show = new javax.swing.JLabel();
        rank3 = new javax.swing.JLabel();
        total_salary_show = new javax.swing.JLabel();

        search_btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        search_btn.setText("Search");

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setText("Search For Employee");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Address:");

        lab.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lab.setText("Rank:");

        rank1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rank1.setText("Hours Worked:");

        rank2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rank2.setText("Over Time:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("ID:");

        id_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        name_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        rank_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        address_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        overtime_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        hours_worked_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        rank3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rank3.setText("Total Salary");

        total_salary_show.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lab)
                                .addComponent(rank1)
                                .addComponent(rank2)
                                .addComponent(rank3)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overtime_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hours_worked_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rank_show, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(id_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(name_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(address_show, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                                    .addComponent(total_salary_show, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 225, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_btn))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(id_show))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name_show))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address_show))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab)
                    .addComponent(rank_show))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rank1)
                    .addComponent(hours_worked_show))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rank2)
                        .addGap(30, 30, 30)
                        .addComponent(rank3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(overtime_show)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_salary_show, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_show;
    private javax.swing.JLabel hours_worked_show;
    private javax.swing.JTextField id;
    private javax.swing.JLabel id_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel name_show;
    private javax.swing.JLabel overtime_show;
    private javax.swing.JLabel rank1;
    private javax.swing.JLabel rank2;
    private javax.swing.JLabel rank3;
    private javax.swing.JLabel rank_show;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel total_salary_show;
    // End of variables declaration//GEN-END:variables
 public Employee find(int id) {//gets the file with employee's data and store the data in Employee obj then return it
        int tempId;
        String tempName = "", tempAddress = "", tempRank = "";
        int tempHours_worked, tempOvertime;
        double tempTotal_salary = 0;
        try {
            Scanner myFile = new Scanner(new File(id + ".txt"));

            tempId = myFile.nextInt();
            tempName = myFile.next();
            tempAddress = myFile.next();
            tempRank = myFile.next();
            tempHours_worked = myFile.nextInt();
            tempOvertime = myFile.nextInt();

            if (myFile.hasNext()) {
                tempTotal_salary = Double.parseDouble(myFile.next());
            } else {
                JOptionPane.showMessageDialog(this, "Employee doesn't have salary", "Error", JOptionPane.ERROR_MESSAGE);
            }

            Employee tempEmployee = new Employee(tempId, tempName, tempAddress, tempRank, tempHours_worked, tempHours_worked);
            tempEmployee.setTotal_salary(tempTotal_salary);
            return tempEmployee;
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Employee Not Found", "Error", JOptionPane.ERROR_MESSAGE);
        }

        Employee tempEmployee = new Employee();
        return tempEmployee;

    }

    ;
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(search_btn)) {
            search_btn.setBackground(Color.black);
            search_btn.setForeground(Color.white);
            Employee tempEmployee = new Employee();

            tempEmployee = find(Integer.parseInt(id.getText()));

            id_show.setText(tempEmployee.getId() + "");
            name_show.setText(tempEmployee.getName());
            address_show.setText(tempEmployee.getAddress());
            rank_show.setText(tempEmployee.getRank());
            hours_worked_show.setText(tempEmployee.getHours_worked() + "");
            overtime_show.setText(tempEmployee.getOvertime_worked() + "");
            total_salary_show.setText(tempEmployee.getTotal_salary() + "");

            search_btn.setBackground(Color.white);
            search_btn.setForeground(Color.black);
        }
    }
}
